version: '3'

services:
  php:
    build: Myphp
    ports:
      - "${HTTPPORT}:80"
      - "${HTTPSPORT}:443"
    volumes:
      - ${FOLDERWWW}:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    volumes:
     - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
    ports:
      - "${MYSQLPORT}:3306"
  phpmyadmin:
    image : phpmyadmin:latest
    volumes:
      - /var/lib/mysql
    ports:
      - "${PHPMYADMINPORT}:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    links:
      - db